/*
 * xparameters_linux.h
 *
 * Linux userspace replacement for the Vitis BSP xparameters.h.
 * Contains ONLY the RFDC-related defines needed by xrfdc_g.c and the
 * application.  All values are taken verbatim from the BSP xparameters.h
 * generated for the T510 / XCZU47DR design.
 *
 * DO NOT add Linux-incompatible definitions (no xparameters_ps.h, etc.).
 */
#ifndef XPARAMETERS_LINUX_H
#define XPARAMETERS_LINUX_H

/* Must be defined so the __BAREMETAL__ path in xrfdc_sinit.c is taken,
 * which uses the static XRFdc_ConfigTable[] from xrfdc_g.c instead of
 * Linux device-tree parsing. */
#define __BAREMETAL__

/* --------------------------------------------------------------------------
 * RF Data Converter (usp_rf_data_converter_0)
 * Source: vitis/t510_standalone_top/.../xparameters.h lines 1494-1873
 * -------------------------------------------------------------------------- */
#define XPAR_XRFDC_NUM_INSTANCES    1U
#define XPAR_XRFDC_0_DEVICE_ID      XPAR_USP_RF_DATA_CONVERTER_0_DEVICE_ID

#define XPAR_USP_RF_DATA_CONVERTER_0_DEVICE_ID        0
#define XPAR_USP_RF_DATA_CONVERTER_0_BASEADDR         0x80000000
#define XPAR_USP_RF_DATA_CONVERTER_0_HIGHADDR         0x8003FFFF
#define XPAR_USP_RF_DATA_CONVERTER_0_HIGH_SPEED_ADC   1
#define XPAR_USP_RF_DATA_CONVERTER_0_SYSREF_MASTER    0
#define XPAR_USP_RF_DATA_CONVERTER_0_SYSREF_SOURCE    1
#define XPAR_USP_RF_DATA_CONVERTER_0_IP_TYPE          2
#define XPAR_USP_RF_DATA_CONVERTER_0_SILICON_REVISION 1

/* DAC Tile 0 */
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_FS_MAX          7.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_LINK_COUPLING   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE00_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL00   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE00     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE00   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE01_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL01   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE01     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE01   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE02_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL02   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE02     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE02   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE03_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL03   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE03     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE03   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE00      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH00     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE00  40
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO00_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER00_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE00     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE01      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH01     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE01  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO01_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER01_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE01     3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE02      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH02     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE02  40
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO02_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER02_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE02     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE03      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH03     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE03  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO03_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER03_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE03     3

/* DAC Tiles 1–3 (same PLL/sampling config as Tile 0) */
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_FS_MAX          7.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_LINK_COUPLING   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE10_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL10   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE10     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE10   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE11_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL11   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE11     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE11   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE12_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL12   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE12     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE12   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE13_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL13   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE13     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE13   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE10      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH10     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE10  20
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO10_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER10_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE10     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE11      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH11     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE11  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO11_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER11_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE11     3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE12      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH12     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE12  20
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO12_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER12_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE12     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE13      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH13     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE13  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO13_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER13_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE13     3

#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_FS_MAX          7.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_LINK_COUPLING   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE20_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL20   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE20     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE20   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE21_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL21   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE21     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE21   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE22_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL22   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE22     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE22   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE23_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL23   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE23     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE23   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE20      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH20     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE20  20
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO20_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER20_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE20     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE21      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH21     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE21  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO21_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER21_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE21     3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE22      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH22     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE22  20
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO22_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER22_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE22     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE23      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH23     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE23  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO23_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER23_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE23     3

#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_FS_MAX          7.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_LINK_COUPLING   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE30_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL30   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE30     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE30   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE31_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL31   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE31     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE31   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE32_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL32   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE32     0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE32   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE33_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL33   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE33     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE33   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE30      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH30     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE30  20
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO30_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER30_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE30     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE31      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH31     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE31  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO31_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER31_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE31     3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE32      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH32     8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE32  20
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO32_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER32_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE32     2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE33      0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH33     16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE33  0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO33_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER33_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE33     3

/* --------------------------------------------------------------------------
 * ADC Tiles 0–3
 * Source: BSP xparameters.h lines 1700-1873
 * -------------------------------------------------------------------------- */
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_FS_MAX          4.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE00_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE00     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE01_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE01     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE02_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE02     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE03_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE03     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE00      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH00     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE00 40
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO00_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE00     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE01      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH01     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE01 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO01_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE01     3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE02      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH02     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE02 40
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO02_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE02     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE03      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH03     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE03 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO03_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE03     3

/* ADC Tiles 1–3 (same config as Tile 0) */
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_FS_MAX          4.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE10_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE10     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE11_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE11     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE12_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE12     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE13_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE13     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE10      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH10     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE10 20
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO10_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE10     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE11      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH11     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE11 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO11_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE11     3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE12      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH12     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE12 20
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO12_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE12     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE13      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH13     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE13 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO13_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE13     3

#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_FS_MAX          4.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE20_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE20     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE21_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE21     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE22_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE22     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE23_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE23     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE20      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH20     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE20 20
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO20_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE20     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE21      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH21     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE21 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO21_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE21     3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE22      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH22     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE22 20
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO22_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE22     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE23      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH23     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE23 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO23_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE23     3

#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_ENABLE         1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_PLL_ENABLE      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_SAMPLING_RATE   4.9152
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_REFCLK_FREQ     4915.200
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_FABRIC_FREQ     61.440
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_FBDIV           10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_OUTDIV          1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_REFCLK_DIV      1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_BAND            0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_FS_MAX          4.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_SLICES          2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE30_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE30     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE31_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE31     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE32_ENABLE   1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE32     0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE33_ENABLE   0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE33     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE30      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH30     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE30 20
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO30_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE30     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE31      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH31     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE31 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO31_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE31     3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE32      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH32     8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE32 20
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO32_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE32     2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE33      0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH33     16
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE33 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO33_ENABLE    0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE33     3

/* Required by xrfdc_g.c but not in the original BSP snippet for ADC
 * (observed pattern from BSP - same values as DAC OUTDIV/FS_MAX etc.) */
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_OUTDIV          2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_OUTDIV          2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_OUTDIV          2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_OUTDIV          2

/* Device name for __BAREMETAL__ xrfdc_sinit.c (not actually used by
 * XRFdc_LookupConfig in baremetal path, but needed for linking) */
#define XPAR_XRFDC_0_DEV_NAME   "80000000.usp_rf_data_converter"

#endif /* XPARAMETERS_LINUX_H */
