<#
===============================================================================
File name:
    create_vivado_review_package.ps1

Purpose:
    Create a Vivado review package from an existing Vivado project.

What it does:
    1. Forces a specific Vivado executable, default Vivado 2024.2.
    2. Opens the given .xpr project in batch mode.
    3. Exports BD Tcl using write_bd_tcl -include_layout.
    4. Generates useful Vivado reports.
    5. Copies HDL/XDC/Tcl/BD/XCI/COE/MEM/log/report files into a timestamped review package.
    6. Creates a ZIP file for sharing with Codex/Claude/ChatGPT or another reviewer.

Usage:
    .\create_vivado_review_package.ps1 `
      -ProjectXpr "D:\Trivedi\2022p2\sdr2\sdr2.xpr"

Optional:
    .\create_vivado_review_package.ps1 `
      -ProjectXpr "D:\Trivedi\2022p2\sdr2\sdr2.xpr" `
      -OutputRoot "D:\Trivedi\2022p2\review_packages" `
      -VivadoBat "D:\Vivado\Vivado\2024.2\bin\vivado.bat"

Notes:
    - This script does not modify the Vivado project.
    - If synthesis/implementation runs are not complete, implementation timing reports
      may be skipped or generated only where runs are available.
===============================================================================
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectXpr,

    [string]$OutputRoot = "",

    [string]$VivadoBat = "D:\Vivado\Vivado\2024.2\bin\vivado.bat",

    [string]$RequiredVivadoVersion = "2024.2",

    [switch]$NoZip
)

$ErrorActionPreference = "Stop"

function Write-Section($Text) {
    Write-Host ""
    Write-Host "===============================================================================" -ForegroundColor Cyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host "===============================================================================" -ForegroundColor Cyan
}

function Ensure-Dir($Path) {
    if (!(Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Copy-IfExists($Src, $DstRoot, $BaseRoot) {
    if (!(Test-Path $Src)) {
        return
    }

    $srcItem = Get-Item $Src

    if ($srcItem.PSIsContainer) {
        return
    }

    $baseFull = (Resolve-Path $BaseRoot).Path.TrimEnd('\') + '\'
    $srcFull  = $srcItem.FullName

    if ($srcFull.StartsWith($baseFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        $rel = $srcFull.Substring($baseFull.Length)
    } else {
        $rel = Split-Path $srcFull -Leaf
    }

    $dst = Join-Path $DstRoot $rel
    $dstDir = Split-Path $dst -Parent
    Ensure-Dir $dstDir
    Copy-Item $srcFull $dst -Force
}

function Copy-MatchingFiles($BaseRoot, $DstRoot, $Patterns) {
    foreach ($pattern in $Patterns) {
        Get-ChildItem -Path $BaseRoot -Recurse -File -Filter $pattern -ErrorAction SilentlyContinue |
            ForEach-Object {
                Copy-IfExists $_.FullName $DstRoot $BaseRoot
            }
    }
}

if (!(Test-Path $ProjectXpr)) {
    throw "Vivado project .xpr not found: $ProjectXpr"
}

if (!(Test-Path $VivadoBat)) {
    throw "Vivado executable not found: $VivadoBat"
}

$ProjectXpr = (Resolve-Path $ProjectXpr).Path
$ProjectDir = Split-Path $ProjectXpr -Parent
$ProjectName = [System.IO.Path]::GetFileNameWithoutExtension($ProjectXpr)

if ($OutputRoot -eq "") {
    $OutputRoot = Join-Path $ProjectDir "review_packages"
}

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$PackageRoot = Join-Path $OutputRoot ("review_" + $ProjectName + "_" + $timestamp)
$SourceCopyDir = Join-Path $PackageRoot "source_snapshot"
$ReportsDir = Join-Path $PackageRoot "reports"
$BdExportDir = Join-Path $PackageRoot "bd_export"
$LogsDir = Join-Path $PackageRoot "vivado_logs"
$ScriptsDir = Join-Path $PackageRoot "scripts"

Write-Section "Creating Review Package Folders"

Ensure-Dir $PackageRoot
Ensure-Dir $SourceCopyDir
Ensure-Dir $ReportsDir
Ensure-Dir $BdExportDir
Ensure-Dir $LogsDir
Ensure-Dir $ScriptsDir

Write-Host "Project       : $ProjectXpr"
Write-Host "Project dir   : $ProjectDir"
Write-Host "Package root  : $PackageRoot"
Write-Host "Vivado        : $VivadoBat"

# -----------------------------------------------------------------------------
# Create Vivado Tcl script for report export.
# -----------------------------------------------------------------------------

$ProjectXprTcl = $ProjectXpr.Replace("\", "/")
$ReportsDirTcl = $ReportsDir.Replace("\", "/")
$BdExportDirTcl = $BdExportDir.Replace("\", "/")
$LogsDirTcl = $LogsDir.Replace("\", "/")
$RequiredVivadoVersionTcl = $RequiredVivadoVersion

$VivadoTcl = @"
# Auto-generated by create_vivado_review_package.ps1

set required_vivado_version "$RequiredVivadoVersionTcl"
set actual_vivado_version [version -short]

puts "Vivado version detected: `$actual_vivado_version"

if {`$actual_vivado_version ne `$required_vivado_version} {
    puts "ERROR: This review package must be generated with Vivado `$required_vivado_version"
    puts "ERROR: Current Vivado version is `$actual_vivado_version"
    exit 1
}

set project_xpr "$ProjectXprTcl"
set reports_dir "$ReportsDirTcl"
set bd_export_dir "$BdExportDirTcl"
set logs_dir "$LogsDirTcl"

file mkdir `$reports_dir
file mkdir `$bd_export_dir
file mkdir `$logs_dir

puts "Opening project: `$project_xpr"
open_project `$project_xpr

set fp [open "`$reports_dir/project_info.txt" "w"]
puts `$fp "Vivado version: [version]"
puts `$fp "Vivado short version: [version -short]"
puts `$fp "Project: `$project_xpr"
puts `$fp "Part: [get_property PART [current_project]]"
puts `$fp "Target language: [get_property TARGET_LANGUAGE [current_project]]"
puts `$fp "Default library: [get_property DEFAULT_LIB [current_project]]"
puts `$fp "Top: [get_property TOP [current_fileset]]"
close `$fp

# Basic project file inventory from Vivado's view.
set fp [open "`$reports_dir/vivado_filesets.txt" "w"]
foreach fs [get_filesets] {
    puts `$fp ""
    puts `$fp "FILESET: `$fs"
    foreach f [get_files -quiet -of_objects `$fs] {
        puts `$fp "  `$f"
    }
}
close `$fp

# Export BD Tcl and validate each BD.
set bd_files [get_files -quiet *.bd]
set fp [open "`$reports_dir/bd_list.txt" "w"]
foreach bd `$bd_files {
    puts `$fp "`$bd"
}
close `$fp

foreach bd `$bd_files {
    puts "Opening BD: `$bd"
    open_bd_design `$bd

    set bd_name [file rootname [file tail `$bd]]

    puts "Validating BD: `$bd_name"
    if {[catch {validate_bd_design} result]} {
        set fp [open "`$reports_dir/`$bd_name`_validate_bd_design_error.txt" "w"]
        puts `$fp `$result
        close `$fp
    } else {
        set fp [open "`$reports_dir/`$bd_name`_validate_bd_design_ok.txt" "w"]
        puts `$fp "validate_bd_design completed without Tcl exception."
        close `$fp
    }

    puts "Exporting BD Tcl: `$bd_name"
    catch {write_bd_tcl -force -include_layout "`$bd_export_dir/`$bd_name`_exported.tcl"} bd_tcl_result

    catch {report_bd_address -file "`$reports_dir/`$bd_name`_bd_address.rpt"} bd_addr_result
}

# IP reports.
catch {report_ip_status -file "`$reports_dir/ip_status.rpt"} ip_status_result
catch {report_property [get_ips] -file "`$reports_dir/ip_properties.rpt"} ip_prop_result

# General design/project reports.
catch {report_compile_order -fileset sources_1 -file "`$reports_dir/compile_order_sources_1.rpt"} compile_result
catch {report_drc -file "`$reports_dir/drc_project.rpt"} drc_project_result
catch {report_methodology -file "`$reports_dir/methodology_project.rpt"} methodology_project_result

# Synthesis reports if synth_1 exists and is complete enough.
if {[llength [get_runs -quiet synth_1]] > 0} {
    set synth_status [get_property STATUS [get_runs synth_1]]
    set fp [open "`$reports_dir/synth_1_status.txt" "w"]
    puts `$fp `$synth_status
    close `$fp

    if {[catch {open_run synth_1} synth_open_result]} {
        set fp [open "`$reports_dir/synth_1_open_error.txt" "w"]
        puts `$fp `$synth_open_result
        close `$fp
    } else {
        catch {report_utilization -file "`$reports_dir/post_synth_utilization.rpt"} synth_util_result
        catch {report_timing_summary -file "`$reports_dir/post_synth_timing_summary.rpt"} synth_timing_result
        catch {report_clock_interaction -file "`$reports_dir/post_synth_clock_interaction.rpt"} synth_clock_result
        catch {report_cdc -file "`$reports_dir/post_synth_cdc.rpt"} synth_cdc_result
        catch {report_drc -file "`$reports_dir/post_synth_drc.rpt"} synth_drc_result
    }
}

# Implementation reports if impl_1 exists and is complete enough.
if {[llength [get_runs -quiet impl_1]] > 0} {
    set impl_status [get_property STATUS [get_runs impl_1]]
    set fp [open "`$reports_dir/impl_1_status.txt" "w"]
    puts `$fp `$impl_status
    close `$fp

    if {[catch {open_run impl_1} impl_open_result]} {
        set fp [open "`$reports_dir/impl_1_open_error.txt" "w"]
        puts `$fp `$impl_open_result
        close `$fp
    } else {
        catch {report_utilization -file "`$reports_dir/post_impl_utilization.rpt"} impl_util_result
        catch {report_timing_summary -file "`$reports_dir/post_impl_timing_summary.rpt"} impl_timing_result
        catch {report_timing -sort_by group -max_paths 100 -file "`$reports_dir/post_impl_timing_100_paths.rpt"} impl_timing_paths_result
        catch {report_clock_interaction -file "`$reports_dir/post_impl_clock_interaction.rpt"} impl_clock_result
        catch {report_cdc -file "`$reports_dir/post_impl_cdc.rpt"} impl_cdc_result
        catch {report_drc -file "`$reports_dir/post_impl_drc.rpt"} impl_drc_result
        catch {report_methodology -file "`$reports_dir/post_impl_methodology.rpt"} impl_methodology_result
        catch {report_power -file "`$reports_dir/post_impl_power.rpt"} impl_power_result
        catch {report_route_status -file "`$reports_dir/post_impl_route_status.rpt"} route_status_result
    }
}

close_project
puts "Vivado review report export completed."
"@

$VivadoTclPath = Join-Path $ScriptsDir "generate_vivado_reports.tcl"
Set-Content -Path $VivadoTclPath -Value $VivadoTcl -Encoding ASCII

# -----------------------------------------------------------------------------
# Run Vivado
# -----------------------------------------------------------------------------

Write-Section "Running Vivado Report Export"

$VivadoLog = Join-Path $LogsDir "vivado_review_export.log"
$VivadoJournal = Join-Path $LogsDir "vivado_review_export.jou"

& $VivadoBat `
    -mode batch `
    -source $VivadoTclPath `
    -log $VivadoLog `
    -journal $VivadoJournal

if ($LASTEXITCODE -ne 0) {
    Write-Host "Vivado returned non-zero exit code: $LASTEXITCODE" -ForegroundColor Yellow
    Write-Host "Check log: $VivadoLog" -ForegroundColor Yellow
}

# -----------------------------------------------------------------------------
# Copy source snapshot.
# -----------------------------------------------------------------------------

Write-Section "Copying Source Snapshot"

$SourcePatterns = @(
    "*.xpr",
    "*.bd",
    "*.tcl",
    "*.xdc",
    "*.v",
    "*.sv",
    "*.vh",
    "*.vhd",
    "*.vhdl",
    "*.xci",
    "*.xcix",
    "component.xml",
    "*.coe",
    "*.mem",
    "*.mif",
    "*.dat",
    "*.hex",
    "*.wcfg",
    "*.do",
    "*.c",
    "*.h",
    "*.cpp",
    "*.hpp",
    "*.py",
    "*.md",
    "*.txt"
)

Copy-MatchingFiles $ProjectDir $SourceCopyDir $SourcePatterns

# Copy existing Vivado logs/reports too, preserving hierarchy.
Write-Section "Copying Existing Logs and Reports"

$ExistingReportDir = Join-Path $PackageRoot "existing_logs_reports"
Ensure-Dir $ExistingReportDir

$ExistingPatterns = @(
    "runme.log",
    "*.rpt",
    "*.log",
    "*.jou"
)

Copy-MatchingFiles $ProjectDir $ExistingReportDir $ExistingPatterns

# -----------------------------------------------------------------------------
# Create package manifest.
# -----------------------------------------------------------------------------

Write-Section "Creating Manifest"

$ManifestPath = Join-Path $PackageRoot "REVIEW_PACKAGE_README.txt"

$ManifestLines = @(
    "Vivado Review Package",
    "=====================",
    "",
    "Project:",
    $ProjectXpr,
    "",
    "Project directory:",
    $ProjectDir,
    "",
    "Generated at:",
    (Get-Date).ToString("yyyy-MM-dd HH:mm:ss"),
    "",
    "Vivado executable:",
    $VivadoBat,
    "",
    "Required Vivado version:",
    $RequiredVivadoVersion,
    "",
    "Package folders:",
    "",
    "bd_export/",
    "  Exported Block Design Tcl files created using write_bd_tcl -include_layout.",
    "",
    "reports/",
    "  Vivado-generated project, BD, IP, timing, DRC, CDC, clock, utilization, power and methodology reports.",
    "",
    "source_snapshot/",
    "  Snapshot of HDL, BD, XDC, Tcl, XCI, COE/MEM, software and documentation files found under the project directory.",
    "",
    "existing_logs_reports/",
    "  Existing .log/.jou/.rpt/runme.log files copied from the project tree.",
    "",
    "vivado_logs/",
    "  Log and journal from this review-package export run.",
    "",
    "scripts/",
    "  Tcl script used to generate the reports."
)

Set-Content -Path $ManifestPath -Value ($ManifestLines -join [Environment]::NewLine) -Encoding UTF8

# -----------------------------------------------------------------------------
# ZIP package.
# -----------------------------------------------------------------------------

if (!$NoZip) {
    Write-Section "Creating ZIP"

    $ZipPath = $PackageRoot + ".zip"

    if (Test-Path $ZipPath) {
        Remove-Item $ZipPath -Force
    }

    Compress-Archive -Path (Join-Path $PackageRoot "*") -DestinationPath $ZipPath -Force

    Write-Host "ZIP created:"
    Write-Host "  $ZipPath"
}

Write-Section "Done"

Write-Host "Review package created:"
Write-Host "  $PackageRoot"

if (!$NoZip) {
    Write-Host ""
    Write-Host "ZIP file:"
    Write-Host "  $($PackageRoot).zip"
}
