<#
===============================================================================
File name:
    prepare_vivado_project_for_review_v3.ps1

Purpose:
    Run this before create_vivado_review_package.ps1.

    This version fixes the BD Tcl export issue caused by Tcl variable expansion
    around names like $bd_name_exported. It uses ${bd_name}_exported.tcl and
    writes explicit diagnostics when BD export fails.

Usage:
    .\prepare_vivado_project_for_review_v3.ps1 `
      -ProjectXpr "D:\Trivedi\2022p2\sdr2\sdr2.xpr" `
      -BuildLevel Implementation `
      -AutoResetRuns

Fast BD/report preparation only:
    .\prepare_vivado_project_for_review_v3.ps1 `
      -ProjectXpr "D:\Trivedi\2022p2\sdr2\sdr2.xpr" `
      -BuildLevel PrepareOnly

BuildLevel options:
    PrepareOnly, Synthesis, Implementation, Bitstream
===============================================================================
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectXpr,

    [string]$VivadoBat = "D:\Vivado\Vivado\2024.2\bin\vivado.bat",

    [string]$RequiredVivadoVersion = "2024.2",

    [ValidateSet("PrepareOnly", "Synthesis", "Implementation", "Bitstream")]
    [string]$BuildLevel = "Implementation",

    [int]$Jobs = 8,

    [switch]$UpgradeIp,

    [switch]$ResetRuns,

    [switch]$AutoResetRuns,

    [switch]$NoZip
)

$ErrorActionPreference = "Stop"

function Write-Section($Text) {
    Write-Host ""
    Write-Host "===============================================================================" -ForegroundColor Cyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host "===============================================================================" -ForegroundColor Cyan
}

function Ensure-Dir($Path) {
    if (!(Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

if (!(Test-Path $ProjectXpr)) {
    throw "Vivado project .xpr not found: $ProjectXpr"
}

if (!(Test-Path $VivadoBat)) {
    throw "Vivado executable not found: $VivadoBat"
}

$ProjectXpr = (Resolve-Path $ProjectXpr).Path
$ProjectDir = Split-Path $ProjectXpr -Parent
$ProjectName = [System.IO.Path]::GetFileNameWithoutExtension($ProjectXpr)

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$PrepRoot = Join-Path $ProjectDir ("review_prepare_" + $ProjectName + "_" + $timestamp)
$ScriptsDir = Join-Path $PrepRoot "scripts"
$ReportsDir = Join-Path $PrepRoot "reports"
$BdExportDir = Join-Path $PrepRoot "bd_export"
$LogsDir = Join-Path $PrepRoot "vivado_logs"

Ensure-Dir $PrepRoot
Ensure-Dir $ScriptsDir
Ensure-Dir $ReportsDir
Ensure-Dir $BdExportDir
Ensure-Dir $LogsDir

Write-Section "Vivado Review Preparation V3"

Write-Host "Project      : $ProjectXpr"
Write-Host "Project dir  : $ProjectDir"
Write-Host "Vivado       : $VivadoBat"
Write-Host "Build level  : $BuildLevel"
Write-Host "Jobs         : $Jobs"
Write-Host "Upgrade IP   : $UpgradeIp"
Write-Host "Reset runs   : $ResetRuns"
Write-Host "Auto reset   : $AutoResetRuns"
Write-Host "Output root  : $PrepRoot"

$ProjectXprTcl = $ProjectXpr.Replace("\", "/")
$ReportsDirTcl = $ReportsDir.Replace("\", "/")
$BdExportDirTcl = $BdExportDir.Replace("\", "/")
$RequiredVivadoVersionTcl = $RequiredVivadoVersion
$BuildLevelTcl = $BuildLevel
$JobsTcl = $Jobs
$UpgradeIpTcl = if ($UpgradeIp) { "1" } else { "0" }
$ResetRunsTcl = if ($ResetRuns) { "1" } else { "0" }
$AutoResetRunsTcl = if ($AutoResetRuns) { "1" } else { "0" }

# Use a single-quoted here-string so PowerShell does not eat Tcl $variables.
$VivadoTclTemplate = @'
# Auto-generated by prepare_vivado_project_for_review_v3.ps1

set required_vivado_version "__REQUIRED_VIVADO_VERSION__"
set actual_vivado_version [version -short]

puts "Vivado version detected: $actual_vivado_version"

if {$actual_vivado_version ne $required_vivado_version} {
    puts "ERROR: This project must be prepared using Vivado $required_vivado_version"
    puts "ERROR: Current Vivado version is $actual_vivado_version"
    exit 1
}

set project_xpr "__PROJECT_XPR__"
set reports_dir "__REPORTS_DIR__"
set bd_export_dir "__BD_EXPORT_DIR__"
set build_level "__BUILD_LEVEL__"
set jobs __JOBS__
set do_upgrade_ip __UPGRADE_IP__
set do_reset_runs __RESET_RUNS__
set do_auto_reset_runs __AUTO_RESET_RUNS__

file mkdir $reports_dir
file mkdir $bd_export_dir

proc write_text_file {path text} {
    set fp [open $path "w"]
    puts $fp $text
    close $fp
}

proc append_text_file {path text} {
    set fp [open $path "a"]
    puts $fp $text
    close $fp
}

proc safe_report {script_body report_path} {
    puts "Generating report: $report_path"
    if {[catch {uplevel 1 $script_body} result]} {
        set err_path "${report_path}.ERROR.txt"
        write_text_file $err_path $result
        puts "WARNING: Failed report: $report_path"
        puts $result
    }
}

puts "Opening project: $project_xpr"
open_project $project_xpr

# -------------------------------------------------------------------------
# Project info
# -------------------------------------------------------------------------

set project_info_path [file join $reports_dir "00_project_info.txt"]
set fp [open $project_info_path "w"]
puts $fp "Vivado version: [version]"
puts $fp "Vivado short version: [version -short]"
puts $fp "Project: $project_xpr"
puts $fp "Part: [get_property PART [current_project]]"
puts $fp "Board part: [get_property BOARD_PART [current_project]]"
puts $fp "Target language: [get_property TARGET_LANGUAGE [current_project]]"
puts $fp "Default library: [get_property DEFAULT_LIB [current_project]]"
puts $fp "Top: [get_property TOP [current_fileset]]"
puts $fp "Build level requested: $build_level"
close $fp

# -------------------------------------------------------------------------
# Optional IP upgrade
# -------------------------------------------------------------------------

if {$do_upgrade_ip} {
    puts "Checking IP upgrade status..."
    set ips_to_upgrade [get_ips -quiet -filter {UPGRADE_VERSIONS != ""}]
    if {[llength $ips_to_upgrade] > 0} {
        puts "Upgrading IPs:"
        foreach ip $ips_to_upgrade {
            puts "  $ip"
        }
        upgrade_ip $ips_to_upgrade
    } else {
        puts "No IPs require upgrade."
    }
}

# -------------------------------------------------------------------------
# File inventory and IP status
# -------------------------------------------------------------------------

set fileset_path [file join $reports_dir "01_filesets_before_prepare.txt"]
set fp [open $fileset_path "w"]
foreach fs [get_filesets] {
    puts $fp ""
    puts $fp "FILESET: $fs"
    foreach f [get_files -quiet -of_objects $fs] {
        puts $fp "  $f"
    }
}
close $fp

catch {report_ip_status -file [file join $reports_dir "02_ip_status_before_prepare.rpt"]}

# -------------------------------------------------------------------------
# Block Design detection
# -------------------------------------------------------------------------

set bd_all_files [get_files -quiet -all *.bd]

# Fallback for some projects/Vivado versions.
if {[llength $bd_all_files] == 0} {
    set all_project_files [get_files -quiet -all]
    foreach f $all_project_files {
        if {[string equal -nocase [file extension $f] ".bd"]} {
            lappend bd_all_files $f
        }
    }
}

# Keep only top-level/user BD files. Exclude generated scoped BD files under .gen,
# such as System ILA internal bd_*.bd files.
set bd_files {}
set bd_skipped_files {}

foreach bd $bd_all_files {
    set bd_norm [string tolower [string map {\\ /} $bd]]
    if {[string match "*.gen/*" $bd_norm] || [string match "*/bd_*/bd_*.bd" $bd_norm]} {
        lappend bd_skipped_files $bd
    } else {
        lappend bd_files $bd
    }
}

set bd_list_path [file join $reports_dir "03_bd_files.txt"]
set fp [open $bd_list_path "w"]
puts $fp "Number of all BD files detected: [llength $bd_all_files]"
puts $fp "Number of top-level/user BD files selected: [llength $bd_files]"
puts $fp ""
puts $fp "SELECTED BD FILES:"
foreach bd $bd_files {
    puts $fp $bd
}
puts $fp ""
puts $fp "SKIPPED GENERATED/SCOPED BD FILES:"
foreach bd $bd_skipped_files {
    puts $fp $bd
}
close $fp

if {[llength $bd_files] == 0} {
    puts "WARNING: No top-level/user BD files detected."
    write_text_file [file join $reports_dir "03_NO_TOP_LEVEL_BD_FILES_FOUND.txt"] "No top-level/user .bd files were detected. Generated/scoped BD files under .gen are intentionally skipped."
}

# -------------------------------------------------------------------------
# Block Design validation, export, address reports, and output products
# -------------------------------------------------------------------------

foreach bd $bd_files {
    set bd_name [file rootname [file tail $bd]]

    puts ""
    puts "Preparing BD: $bd_name"
    puts "BD file: $bd"

    if {[catch {open_bd_design $bd} open_bd_result]} {
        write_text_file [file join $reports_dir "${bd_name}_open_bd_design_ERROR.txt"] $open_bd_result
        puts "ERROR: open_bd_design failed for $bd"
        puts $open_bd_result
        continue
    }

    puts "Validating BD: $bd_name"
    if {[catch {validate_bd_design} validate_result]} {
        write_text_file [file join $reports_dir "${bd_name}_validate_bd_design_ERROR.txt"] $validate_result
    } else {
        write_text_file [file join $reports_dir "${bd_name}_validate_bd_design_OK.txt"] "validate_bd_design passed without Tcl exception."
    }

    puts "Saving BD: $bd_name"
    catch {save_bd_design} save_bd_result

    puts "Exporting BD Tcl: $bd_name"
    set bd_tcl_out [file join $bd_export_dir "${bd_name}_exported.tcl"]
    if {[catch {write_bd_tcl -force -include_layout $bd_tcl_out} bd_tcl_result]} {
        write_text_file [file join $reports_dir "${bd_name}_write_bd_tcl_ERROR.txt"] $bd_tcl_result
        puts "ERROR: write_bd_tcl failed for $bd_name"
        puts $bd_tcl_result
    } else {
        write_text_file [file join $reports_dir "${bd_name}_write_bd_tcl_OK.txt"] "BD Tcl exported to: $bd_tcl_out"
        puts "BD Tcl exported to: $bd_tcl_out"
    }

    puts "Reporting BD address: $bd_name"
    catch {report_bd_address -file [file join $reports_dir "${bd_name}_bd_address.rpt"]} bd_addr_result

    puts "Generating BD output products: $bd_name"
    catch {generate_target all [get_files $bd]} gen_bd_result

    puts "Creating BD wrapper if needed: $bd_name"
    catch {make_wrapper -files [get_files $bd] -top} wrapper_result
}

# -------------------------------------------------------------------------
# IP output products
# -------------------------------------------------------------------------

set ip_files [get_files -quiet -all *.xci]
set ip_list_path [file join $reports_dir "04_xci_files.txt"]
set fp [open $ip_list_path "w"]
puts $fp "Number of XCI files detected: [llength $ip_files]"
foreach xci $ip_files {
    puts $fp $xci
}
close $fp

foreach xci $ip_files {
    puts "Generating IP output products for: $xci"
    catch {generate_target all [get_files $xci]} gen_ip_result
}

catch {export_ip_user_files -of_objects [get_files -quiet -all *.xci] -no_script -sync -force -quiet} export_ip_result

# -------------------------------------------------------------------------
# Compile order and sanity reports
# -------------------------------------------------------------------------

puts "Updating compile order..."
catch {update_compile_order -fileset sources_1} update_sources_result
catch {update_compile_order -fileset sim_1} update_sim_result

catch {report_compile_order -fileset sources_1 -file [file join $reports_dir "05_compile_order_sources_1.rpt"]}
catch {report_compile_order -fileset sim_1     -file [file join $reports_dir "06_compile_order_sim_1.rpt"]}

catch {report_ip_status   -file [file join $reports_dir "07_ip_status_after_prepare.rpt"]}
catch {report_drc         -file [file join $reports_dir "08_project_drc_after_prepare.rpt"]}
catch {report_methodology -file [file join $reports_dir "09_project_methodology_after_prepare.rpt"]}

# -------------------------------------------------------------------------
# Run helper
# -------------------------------------------------------------------------

proc launch_run_with_optional_auto_reset {run_name args_list auto_reset reports_dir} {
    puts "Launching $run_name with args: $args_list"

    set cmd [concat [list launch_runs $run_name] $args_list]
    set rc [catch {eval $cmd} result]

    if {$rc} {
        puts "launch_runs failed for $run_name:"
        puts $result

        if {$auto_reset && [string match -nocase "*needs to be reset before launching*" $result]} {
            puts "Auto-reset enabled. Resetting $run_name and launching again."
            catch {reset_run $run_name} reset_result

            set rc2 [catch {eval $cmd} result2]
            if {$rc2} {
                write_text_file [file join $reports_dir "${run_name}_launch_after_reset_ERROR.txt"] $result2
                return -code error $result2
            } else {
                return $result2
            }
        } else {
            write_text_file [file join $reports_dir "${run_name}_launch_ERROR.txt"] $result
            return -code error $result
        }
    }

    return $result
}

# -------------------------------------------------------------------------
# Runs
# -------------------------------------------------------------------------

if {$do_reset_runs} {
    puts "Resetting synth_1 and impl_1 runs because -ResetRuns was requested."
    catch {reset_run synth_1}
    catch {reset_run impl_1}
}

set run_synth 0
set run_impl 0
set write_bitstream 0

if {$build_level eq "Synthesis"} {
    set run_synth 1
}
if {$build_level eq "Implementation"} {
    set run_synth 1
    set run_impl 1
}
if {$build_level eq "Bitstream"} {
    set run_synth 1
    set run_impl 1
    set write_bitstream 1
}

if {$build_level eq "PrepareOnly"} {
    puts "BuildLevel=PrepareOnly. Synthesis and implementation will not be launched."
}

if {$run_synth} {
    if {[llength [get_runs -quiet synth_1]] == 0} {
        puts "ERROR: synth_1 run not found."
        exit 1
    }

    puts "Launching synth_1..."
    if {[catch {launch_run_with_optional_auto_reset synth_1 [list -jobs $jobs] $do_auto_reset_runs $reports_dir} synth_launch_result]} {
        puts "ERROR: synth_1 launch failed."
        puts $synth_launch_result
        exit 1
    }
    wait_on_run synth_1

    set synth_status [get_property STATUS [get_runs synth_1]]
    write_text_file [file join $reports_dir "10_synth_1_status.txt"] $synth_status

    if {[catch {open_run synth_1} synth_open_result]} {
        write_text_file [file join $reports_dir "11_synth_1_open_ERROR.txt"] $synth_open_result
    } else {
        catch {report_utilization       -file [file join $reports_dir "12_post_synth_utilization.rpt"]}
        catch {report_timing_summary    -file [file join $reports_dir "13_post_synth_timing_summary.rpt"]}
        catch {report_clock_interaction -file [file join $reports_dir "14_post_synth_clock_interaction.rpt"]}
        catch {report_cdc               -file [file join $reports_dir "15_post_synth_cdc.rpt"]}
        catch {report_drc               -file [file join $reports_dir "16_post_synth_drc.rpt"]}
        catch {report_methodology       -file [file join $reports_dir "17_post_synth_methodology.rpt"]}
    }
}

if {$run_impl} {
    if {[llength [get_runs -quiet impl_1]] == 0} {
        puts "ERROR: impl_1 run not found."
        exit 1
    }

    if {$write_bitstream} {
        puts "Launching impl_1 to write_bitstream..."
        set impl_args [list -to_step write_bitstream -jobs $jobs]
    } else {
        puts "Launching impl_1 to route_design..."
        set impl_args [list -to_step route_design -jobs $jobs]
    }

    if {[catch {launch_run_with_optional_auto_reset impl_1 $impl_args $do_auto_reset_runs $reports_dir} impl_launch_result]} {
        puts "ERROR: impl_1 launch failed."
        puts $impl_launch_result
        exit 1
    }

    wait_on_run impl_1

    set impl_status [get_property STATUS [get_runs impl_1]]
    write_text_file [file join $reports_dir "18_impl_1_status.txt"] $impl_status

    if {[catch {open_run impl_1} impl_open_result]} {
        write_text_file [file join $reports_dir "19_impl_1_open_ERROR.txt"] $impl_open_result
    } else {
        catch {report_utilization       -file [file join $reports_dir "20_post_impl_utilization.rpt"]}
        catch {report_timing_summary    -file [file join $reports_dir "21_post_impl_timing_summary.rpt"]}
        catch {report_timing -sort_by group -max_paths 100 -file [file join $reports_dir "22_post_impl_timing_100_paths.rpt"]}
        catch {report_clock_interaction -file [file join $reports_dir "23_post_impl_clock_interaction.rpt"]}
        catch {report_cdc               -file [file join $reports_dir "24_post_impl_cdc.rpt"]}
        catch {report_drc               -file [file join $reports_dir "25_post_impl_drc.rpt"]}
        catch {report_methodology       -file [file join $reports_dir "26_post_impl_methodology.rpt"]}
        catch {report_power             -file [file join $reports_dir "27_post_impl_power.rpt"]}
        catch {report_route_status      -file [file join $reports_dir "28_post_impl_route_status.rpt"]}
    }
}

# -------------------------------------------------------------------------
# Final inventory
# -------------------------------------------------------------------------

set fileset_after_path [file join $reports_dir "29_filesets_after_prepare.txt"]
set fp [open $fileset_after_path "w"]
foreach fs [get_filesets] {
    puts $fp ""
    puts $fp "FILESET: $fs"
    foreach f [get_files -quiet -of_objects $fs] {
        puts $fp "  $f"
    }
}
close $fp

close_project

puts ""
puts "Vivado project preparation completed."
puts "Reports generated in: $reports_dir"
puts "BD Tcl exported in: $bd_export_dir"
'@

$VivadoTcl = $VivadoTclTemplate.
    Replace("__REQUIRED_VIVADO_VERSION__", $RequiredVivadoVersionTcl).
    Replace("__PROJECT_XPR__", $ProjectXprTcl).
    Replace("__REPORTS_DIR__", $ReportsDirTcl).
    Replace("__BD_EXPORT_DIR__", $BdExportDirTcl).
    Replace("__BUILD_LEVEL__", $BuildLevelTcl).
    Replace("__JOBS__", [string]$JobsTcl).
    Replace("__UPGRADE_IP__", [string]$UpgradeIpTcl).
    Replace("__RESET_RUNS__", [string]$ResetRunsTcl)

$VivadoTclPath = Join-Path $ScriptsDir "prepare_vivado_project_for_review_v3.tcl"
Set-Content -Path $VivadoTclPath -Value $VivadoTcl -Encoding ASCII

Write-Section "Running Vivado"

$VivadoLog = Join-Path $LogsDir "prepare_vivado_project_for_review_v3.log"
$VivadoJournal = Join-Path $LogsDir "prepare_vivado_project_for_review_v3.jou"

& $VivadoBat `
    -mode batch `
    -source $VivadoTclPath `
    -log $VivadoLog `
    -journal $VivadoJournal

$VivadoExit = $LASTEXITCODE

if ($VivadoExit -ne 0) {
    Write-Host ""
    Write-Host "Vivado returned non-zero exit code: $VivadoExit" -ForegroundColor Yellow
    Write-Host "Check log:"
    Write-Host "  $VivadoLog"
} else {
    Write-Host ""
    Write-Host "Vivado preparation completed successfully."
}

Write-Section "Creating Preparation Summary"

$SummaryPath = Join-Path $PrepRoot "PREPARE_SUMMARY.txt"

$SummaryLines = @(
    "Vivado Project Preparation Summary",
    "==================================",
    "",
    "Project:",
    $ProjectXpr,
    "",
    "Vivado:",
    $VivadoBat,
    "",
    "Required Vivado version:",
    $RequiredVivadoVersion,
    "",
    "Build level:",
    $BuildLevel,
    "",
    "Jobs:",
    $Jobs.ToString(),
    "",
    "Upgrade IP:",
    $UpgradeIp.ToString(),
    "",
    "Reset runs:",
    $ResetRuns.ToString(),
    "",
    "Auto reset runs:",
    $AutoResetRuns.ToString(),
    "",
    "Vivado exit code:",
    $VivadoExit.ToString(),
    "",
    "Preparation root:",
    $PrepRoot,
    "",
    "Reports:",
    $ReportsDir,
    "",
    "BD exports:",
    $BdExportDir,
    "",
    "Vivado log:",
    $VivadoLog,
    "",
    "Generated Vivado Tcl:",
    $VivadoTclPath,
    "",
    "Quick checks:",
    "  Check BD list:       reports\03_bd_files.txt",
    "  Check BD export OK:  reports\*_write_bd_tcl_OK.txt",
    "  Check BD export err: reports\*_write_bd_tcl_ERROR.txt",
    "",
    "Next recommended command:",
    ".\create_vivado_review_package.ps1 -ProjectXpr `"$ProjectXpr`""
)

Set-Content -Path $SummaryPath -Value ($SummaryLines -join [Environment]::NewLine) -Encoding UTF8

if (!$NoZip) {
    Write-Section "Creating Preparation ZIP"

    $ZipPath = $PrepRoot + ".zip"
    if (Test-Path $ZipPath) {
        Remove-Item $ZipPath -Force
    }

    Compress-Archive -Path (Join-Path $PrepRoot "*") -DestinationPath $ZipPath -Force

    Write-Host "ZIP created:"
    Write-Host "  $ZipPath"
}

Write-Section "Done"

Write-Host "Preparation output:"
Write-Host "  $PrepRoot"

if (!$NoZip) {
    Write-Host ""
    Write-Host "ZIP:"
    Write-Host "  $($PrepRoot).zip"
}

Write-Host ""
Write-Host "Check BD export:"
Write-Host "  Get-ChildItem `"$BdExportDir`""
Write-Host ""
Write-Host "If BD export is still empty, inspect:"
Write-Host "  Get-Content `"$ReportsDir\03_bd_files.txt`""
Write-Host "  Get-ChildItem `"$ReportsDir`" -Filter `"*_write_bd_tcl*`""
Write-Host "  Get-Content `"$VivadoLog`" -Tail 100"
Write-Host ""
Write-Host "Now create the review package:"
Write-Host "  .\create_vivado_review_package.ps1 -ProjectXpr `"$ProjectXpr`""
