proc getPresetInfo {} {
  return [dict create name {rf_data_config.tcl} description {rf_data_config.tcl}  vlnv xilinx.com:ip:usp_rf_data_converter:2.6 display_name {rf_data_config.tcl} ]
}

proc validate_preset {IPINST} { return true }


proc apply_preset {IPINST} {
  return [dict create \
    CONFIG.ADC0_Sampling_Rate {4.9152}  \
    CONFIG.ADC0_Refclk_Freq {4915.200}  \
    CONFIG.ADC0_Outclk_Freq {38.400}  \
    CONFIG.ADC0_Fabric_Freq {61.440}  \
    CONFIG.ADC0_Multi_Tile_Sync {true}  \
    CONFIG.ADC0_Clock_Source {1}  \
    CONFIG.ADC_Data_Type00 {1}  \
    CONFIG.ADC_Decimation_Mode00 {20}  \
    CONFIG.ADC_Mixer_Type00 {2}  \
    CONFIG.ADC_Mixer_Mode00 {0}  \
    CONFIG.ADC_Data_Width00 {4}  \
    CONFIG.ADC_Coarse_Mixer_Freq00 {0}  \
    CONFIG.ADC_NCO_Freq00 {1.5}  \
    CONFIG.ADC_Data_Type01 {1}  \
    CONFIG.ADC_Decimation_Mode01 {20}  \
    CONFIG.ADC_Mixer_Type01 {2}  \
    CONFIG.ADC_Mixer_Mode01 {0}  \
    CONFIG.ADC_Data_Width01 {4}  \
    CONFIG.ADC_Coarse_Mixer_Freq01 {0}  \
    CONFIG.ADC_NCO_Freq01 {1.5}  \
    CONFIG.ADC_Slice02_Enable {true}  \
    CONFIG.ADC_Data_Type02 {1}  \
    CONFIG.ADC_Decimation_Mode02 {20}  \
    CONFIG.ADC_Mixer_Type02 {2}  \
    CONFIG.ADC_Mixer_Mode02 {0}  \
    CONFIG.ADC_Data_Width02 {4}  \
    CONFIG.ADC_NCO_Freq02 {1.5}  \
    CONFIG.ADC_Slice03_Enable {true}  \
    CONFIG.ADC_Data_Type03 {1}  \
    CONFIG.ADC_Decimation_Mode03 {20}  \
    CONFIG.ADC_Mixer_Type03 {2}  \
    CONFIG.ADC_Mixer_Mode03 {0}  \
    CONFIG.ADC_Data_Width03 {4}  \
    CONFIG.ADC_NCO_Freq03 {1.5}  \
    CONFIG.ADC1_Enable {1}  \
    CONFIG.ADC1_PLL_Enable {true}  \
    CONFIG.ADC1_Sampling_Rate {4.9152}  \
    CONFIG.ADC1_Refclk_Freq {245.760}  \
    CONFIG.ADC1_Outclk_Freq {38.400}  \
    CONFIG.ADC1_Fabric_Freq {61.440}  \
    CONFIG.ADC1_Multi_Tile_Sync {true}  \
    CONFIG.ADC1_Clock_Dist {2}  \
    CONFIG.ADC_Slice10_Enable {true}  \
    CONFIG.ADC_Data_Type10 {1}  \
    CONFIG.ADC_Decimation_Mode10 {20}  \
    CONFIG.ADC_Mixer_Type10 {2}  \
    CONFIG.ADC_Mixer_Mode10 {0}  \
    CONFIG.ADC_Data_Width10 {4}  \
    CONFIG.ADC_NCO_Freq10 {1.5}  \
    CONFIG.ADC_Slice11_Enable {true}  \
    CONFIG.ADC_Data_Type11 {1}  \
    CONFIG.ADC_Decimation_Mode11 {20}  \
    CONFIG.ADC_Mixer_Type11 {2}  \
    CONFIG.ADC_Mixer_Mode11 {0}  \
    CONFIG.ADC_Data_Width11 {4}  \
    CONFIG.ADC_NCO_Freq11 {1.5}  \
    CONFIG.ADC_Slice12_Enable {true}  \
    CONFIG.ADC_Data_Type12 {1}  \
    CONFIG.ADC_Decimation_Mode12 {20}  \
    CONFIG.ADC_Mixer_Type12 {2}  \
    CONFIG.ADC_Mixer_Mode12 {0}  \
    CONFIG.ADC_Data_Width12 {4}  \
    CONFIG.ADC_NCO_Freq12 {1.5}  \
    CONFIG.ADC_Slice13_Enable {true}  \
    CONFIG.ADC_Data_Type13 {1}  \
    CONFIG.ADC_Decimation_Mode13 {20}  \
    CONFIG.ADC_Mixer_Type13 {2}  \
    CONFIG.ADC_Mixer_Mode13 {0}  \
    CONFIG.ADC_Data_Width13 {4}  \
    CONFIG.ADC_NCO_Freq13 {1.5}  \
    CONFIG.ADC2_Enable {1}  \
    CONFIG.ADC2_Sampling_Rate {4.9152}  \
    CONFIG.ADC2_Refclk_Freq {4915.200}  \
    CONFIG.ADC2_Outclk_Freq {38.400}  \
    CONFIG.ADC2_Fabric_Freq {61.440}  \
    CONFIG.ADC2_Multi_Tile_Sync {true}  \
    CONFIG.ADC2_Clock_Source {1}  \
    CONFIG.ADC_Slice20_Enable {true}  \
    CONFIG.ADC_Data_Type20 {1}  \
    CONFIG.ADC_Decimation_Mode20 {20}  \
    CONFIG.ADC_Mixer_Type20 {2}  \
    CONFIG.ADC_Mixer_Mode20 {0}  \
    CONFIG.ADC_Data_Width20 {4}  \
    CONFIG.ADC_NCO_Freq20 {1.5}  \
    CONFIG.ADC_Slice21_Enable {true}  \
    CONFIG.ADC_Data_Type21 {1}  \
    CONFIG.ADC_Decimation_Mode21 {20}  \
    CONFIG.ADC_Mixer_Type21 {2}  \
    CONFIG.ADC_Mixer_Mode21 {0}  \
    CONFIG.ADC_Data_Width21 {4}  \
    CONFIG.ADC_NCO_Freq21 {1.5}  \
    CONFIG.ADC_Slice22_Enable {true}  \
    CONFIG.ADC_Data_Type22 {1}  \
    CONFIG.ADC_Decimation_Mode22 {20}  \
    CONFIG.ADC_Mixer_Type22 {2}  \
    CONFIG.ADC_Mixer_Mode22 {0}  \
    CONFIG.ADC_Data_Width22 {4}  \
    CONFIG.ADC_NCO_Freq22 {1.5}  \
    CONFIG.ADC_Slice23_Enable {true}  \
    CONFIG.ADC_Data_Type23 {1}  \
    CONFIG.ADC_Decimation_Mode23 {20}  \
    CONFIG.ADC_Mixer_Type23 {2}  \
    CONFIG.ADC_Mixer_Mode23 {0}  \
    CONFIG.ADC_Data_Width23 {4}  \
    CONFIG.ADC_NCO_Freq23 {1.5}  \
    CONFIG.ADC3_Enable {1}  \
    CONFIG.ADC3_Sampling_Rate {4.9152}  \
    CONFIG.ADC3_Refclk_Freq {4915.200}  \
    CONFIG.ADC3_Outclk_Freq {38.400}  \
    CONFIG.ADC3_Fabric_Freq {61.440}  \
    CONFIG.ADC3_Multi_Tile_Sync {true}  \
    CONFIG.ADC3_Clock_Source {1}  \
    CONFIG.ADC_Slice30_Enable {true}  \
    CONFIG.ADC_Data_Type30 {1}  \
    CONFIG.ADC_Decimation_Mode30 {20}  \
    CONFIG.ADC_Mixer_Type30 {2}  \
    CONFIG.ADC_Mixer_Mode30 {0}  \
    CONFIG.ADC_Data_Width30 {4}  \
    CONFIG.ADC_NCO_Freq30 {1.5}  \
    CONFIG.ADC_Slice31_Enable {true}  \
    CONFIG.ADC_Data_Type31 {1}  \
    CONFIG.ADC_Decimation_Mode31 {20}  \
    CONFIG.ADC_Mixer_Type31 {2}  \
    CONFIG.ADC_Mixer_Mode31 {0}  \
    CONFIG.ADC_Data_Width31 {4}  \
    CONFIG.ADC_NCO_Freq31 {1.5}  \
    CONFIG.ADC_Slice32_Enable {true}  \
    CONFIG.ADC_Data_Type32 {1}  \
    CONFIG.ADC_Decimation_Mode32 {20}  \
    CONFIG.ADC_Mixer_Type32 {2}  \
    CONFIG.ADC_Mixer_Mode32 {0}  \
    CONFIG.ADC_Data_Width32 {4}  \
    CONFIG.ADC_NCO_Freq32 {1.5}  \
    CONFIG.ADC_Slice33_Enable {true}  \
    CONFIG.ADC_Data_Type33 {1}  \
    CONFIG.ADC_Decimation_Mode33 {20}  \
    CONFIG.ADC_Mixer_Type33 {2}  \
    CONFIG.ADC_Mixer_Mode33 {0}  \
    CONFIG.ADC_Data_Width33 {4}  \
    CONFIG.ADC_NCO_Freq33 {1.5}  \
    CONFIG.DAC0_Enable {1}  \
    CONFIG.DAC0_Sampling_Rate {4.9152}  \
    CONFIG.DAC0_Refclk_Freq {4915.200}  \
    CONFIG.DAC0_Outclk_Freq {38.400}  \
    CONFIG.DAC0_Fabric_Freq {61.440}  \
    CONFIG.DAC0_Multi_Tile_Sync {true}  \
    CONFIG.DAC0_Clock_Source {6}  \
    CONFIG.DAC_Slice00_Enable {true}  \
    CONFIG.DAC_Data_Type00 {0}  \
    CONFIG.DAC_Data_Width00 {8}  \
    CONFIG.DAC_Interpolation_Mode00 {20}  \
    CONFIG.DAC_Mixer_Type00 {2}  \
    CONFIG.DAC_Mixer_Mode00 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq00 {3}  \
    CONFIG.DAC_NCO_Freq00 {1.5}  \
    CONFIG.DAC_Slice02_Enable {true}  \
    CONFIG.DAC_Data_Width02 {8}  \
    CONFIG.DAC_Interpolation_Mode02 {20}  \
    CONFIG.DAC_Mixer_Type02 {2}  \
    CONFIG.DAC_Mixer_Mode02 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq02 {3}  \
    CONFIG.DAC_NCO_Freq02 {1.5}  \
    CONFIG.DAC1_Enable {1}  \
    CONFIG.DAC1_Sampling_Rate {4.9152}  \
    CONFIG.DAC1_Refclk_Freq {4915.200}  \
    CONFIG.DAC1_Outclk_Freq {38.400}  \
    CONFIG.DAC1_Fabric_Freq {61.440}  \
    CONFIG.DAC1_Multi_Tile_Sync {true}  \
    CONFIG.DAC1_Clock_Source {6}  \
    CONFIG.DAC_Slice10_Enable {true}  \
    CONFIG.DAC_Data_Width10 {8}  \
    CONFIG.DAC_Interpolation_Mode10 {20}  \
    CONFIG.DAC_Mixer_Type10 {2}  \
    CONFIG.DAC_Mixer_Mode10 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq10 {3}  \
    CONFIG.DAC_NCO_Freq10 {1.5}  \
    CONFIG.DAC_Slice12_Enable {true}  \
    CONFIG.DAC_Data_Width12 {8}  \
    CONFIG.DAC_Interpolation_Mode12 {20}  \
    CONFIG.DAC_Mixer_Type12 {2}  \
    CONFIG.DAC_Mixer_Mode12 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq12 {3}  \
    CONFIG.DAC_NCO_Freq12 {1.5}  \
    CONFIG.DAC2_Enable {1}  \
    CONFIG.DAC2_PLL_Enable {true}  \
    CONFIG.DAC2_Sampling_Rate {4.9152}  \
    CONFIG.DAC2_Refclk_Freq {245.760}  \
    CONFIG.DAC2_Outclk_Freq {38.400}  \
    CONFIG.DAC2_Fabric_Freq {61.440}  \
    CONFIG.DAC2_Multi_Tile_Sync {true}  \
    CONFIG.DAC2_Clock_Dist {2}  \
    CONFIG.DAC_Slice20_Enable {true}  \
    CONFIG.DAC_Data_Width20 {8}  \
    CONFIG.DAC_Interpolation_Mode20 {20}  \
    CONFIG.DAC_Mixer_Type20 {2}  \
    CONFIG.DAC_Mixer_Mode20 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq20 {3}  \
    CONFIG.DAC_NCO_Freq20 {1.5}  \
    CONFIG.DAC_Slice22_Enable {true}  \
    CONFIG.DAC_Data_Width22 {8}  \
    CONFIG.DAC_Interpolation_Mode22 {20}  \
    CONFIG.DAC_Mixer_Type22 {2}  \
    CONFIG.DAC_Mixer_Mode22 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq22 {3}  \
    CONFIG.DAC_NCO_Freq22 {1.5}  \
    CONFIG.DAC3_Enable {1}  \
    CONFIG.DAC3_Sampling_Rate {4.9152}  \
    CONFIG.DAC3_Refclk_Freq {4915.200}  \
    CONFIG.DAC3_Outclk_Freq {38.400}  \
    CONFIG.DAC3_Fabric_Freq {61.440}  \
    CONFIG.DAC3_Multi_Tile_Sync {true}  \
    CONFIG.DAC3_Clock_Source {6}  \
    CONFIG.DAC_Slice30_Enable {true}  \
    CONFIG.DAC_Data_Type30 {0}  \
    CONFIG.DAC_Data_Width30 {8}  \
    CONFIG.DAC_Interpolation_Mode30 {20}  \
    CONFIG.DAC_Mixer_Type30 {2}  \
    CONFIG.DAC_Mixer_Mode30 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq30 {3}  \
    CONFIG.DAC_NCO_Freq30 {1.5}  \
    CONFIG.DAC_Slice32_Enable {true}  \
    CONFIG.DAC_Data_Width32 {8}  \
    CONFIG.DAC_Interpolation_Mode32 {20}  \
    CONFIG.DAC_Mixer_Type32 {2}  \
    CONFIG.DAC_Mixer_Mode32 {0}  \
    CONFIG.DAC_Coarse_Mixer_Freq32 {3}  \
    CONFIG.DAC_NCO_Freq32 {1.5}  \
  ]
}


